import { ATTRIBUTES, type AttributeLabel, type Id } from "../types/BoundTypes"
import type { ItemLabel } from "./bindings"

export const GROUP = {
	CONS: {key: 0, label: 'consumables'},
	ATTR: {key: 1, label: 'attributes'},
	EQUI: {key: 2, label: 'equipment'},
	MISC: {key: 3, label: 'miscellaneous'},
	SECR: {key: 4, label: 'secret shop'},
	ACCE: {key: 5, label: 'accessories'},
	SUPP: {key: 6, label: 'support'},
	MAGI: {key: 7, label: 'magical'},
	ARMO: {key: 8, label: 'armor'},
	WEAP: {key: 9, label: 'weapons'},
	ARMA: {key: 10, label: 'armaments'},
	ARTI: {key: 11, label: 'neutral artifacts'},
	ENCH: {key: 12, label: 'neutral enchantments'},
	UNIT: {key: 13, label: 'unit specific'},
	OUT: {key: 14, label: 'retired'},
	WIP: {key: 15, label: 'not implemented'},
} as const satisfies Record<string, Id>

type GroupKey = typeof GROUP[keyof typeof GROUP]['key']
export type GroupName = keyof typeof GROUP

export const GROUP_BY_ITEM = {
	//BASICS
	//Consumables
	tpscroll: 0,
	clarity: 0,
	faerie_fire: 0,
	smoke_of_deceit: 0,
	ward_observer: 0,
	ward_sentry: 0,
	enchanted_mango: 0,
	flask: 0,
	tango: 0,
	blood_grenade: 0,
	dust: 0,
	bottle: 0,
	infused_raindrop: 0,
	aghanims_shard: 0,
	//Attributes
	branches: 1,
	gauntlets: 1,
	slippers: 1,
	mantle: 1,
	circlet: 1,
	belt_of_strength: 1,
	boots_of_elves: 1,
	robe: 1,
	crown: 1,
	ogre_axe: 1,
	blade_of_alacrity: 1,
	staff_of_wizardry: 1,
	diadem: 1,
	ghost: 1,
	//Equipment
	quelling_blade: 2,
	ring_of_protection: 2,
	blades_of_attack: 2,
	orb_of_frost: 2,
	gloves: 2,
	chainmail: 2,
	broadsword: 2,
	blight_stone: 2,
	blitz_knuckles: 2,
	splintmail: 2,
	claymore: 2,
	orb_of_venom: 2,
	javelin: 2,
	helm_of_iron_will: 2,
	mithril_hammer: 2,
	//Misc.
	ring_of_regen: 3,
	sobi_mask: 3,
	wind_lace: 3,
	magic_stick: 3,
	fluffy_hat: 3,
	wizard_hat: 3,
	boots: 3,
	voodoo_mask: 3,
	shawl: 3,
	shadow_amulet: 3,
	gem: 3,
	lifesteal: 3,
	cloak: 3,
	chasm_stone: 3,
	blink: 3,
	//Secret shop
	ring_of_health: 4,
	void_stone: 4,
	talisman_of_evasion: 4,
	platemail: 4,
	ring_of_tarrasque: 4,
	tiara_of_selemene: 4,
	hyperstone: 4,
	demon_edge: 4,
	vitality_booster: 4,
	energy_booster: 4,
	point_booster: 4,
	relic: 4,
	reaver: 4,
	eagle: 4,
	mystic_staff: 4,
	ultimate_orb: 4,
	//UPGRADES
	//accessories
	magic_wand: 5,
	bracer: 5,
	wraith_band: 5,
	null_talisman: 5,
	power_treads: 5,
	soul_ring: 5,
	orb_of_corrosion: 5,
	falcon_blade: 5,
	phase_boots: 5,
	pers: 5,
	mask_of_madness: 5,
	oblivion_staff: 5,
	travel_boots: 5,
	hand_of_midas: 5,
	moon_shard: 5,
	soul_booster: 5,
	//Support
	ring_of_basilius: 6,
	headdress: 6,
	urn_of_shadows: 6,
	tranquil_boots: 6,
	arcane_boots: 6,
	mekansm: 6,
	essence_distiller: 6,
	ancient_janggo: 6,
	pavise: 6,
	guardian_greaves: 6,
	spirit_vessel: 6,
	boots_of_bearing: 6,
	solar_crest: 6,
	glimmer_cape: 6,
	holy_locket: 6,
	pipe: 6,
	//Magical
	veil_of_discord: 7,
	rod_of_atos: 7,
	cyclone: 7,
	phylactery: 7,
	bloodstone: 7,
	gungir: 7,
	wind_waker: 7,
	angels_demise: 7,
	force_staff: 7,
	aether_lens: 7,
	meteor_hammer: 7,
	dagon: 7,
	ultimate_scepter: 7,
	crellas_crozier: 7,
	octarine_core: 7,
	orchid: 7,
	refresher: 7,
	ethereal_blade: 7,
	sheepstick: 7,
	bloodthorn: 7,
	//Armor
	buckler: 8,
	vanguard: 8,
	blade_mail: 8,
	helm_of_the_dominator: 8,
	vladmir: 8,
	crimson_guard: 8,
	armlet: 8,
	helm_of_the_overlord: 8,
	consecrated_wraps: 8,
	aeon_disk: 8,
	lotus_orb: 8,
	black_king_bar: 8,
	shivas_guard: 8,
	sphere: 8,
	assault: 8,
	heart: 8,
	//Weapons
	lesser_crit: 9,
	mage_slayer: 9,
	heavens_halberd: 9,
	desolator: 9,
	revenants_brooch: 9,
	basher: 9,
	maelstrom: 9,
	invis_sword: 9,
	greater_crit: 9,
	abyssal_blade: 9,
	mjollnir: 9,
	silver_edge: 9,
	bfury: 9,
	nullifier: 9,
	manta: 9,
	radiance: 9,
	rapier: 9,
	monkey_king_bar: 9,
	butterfly: 9,
	satanic: 9,
	//Armaments
	sange: 10,
	yasha: 10,
	kaya: 10,
	dragon_lance: 10,
	kaya_and_sange: 10,
	sange_and_yasha: 10,
	yasha_and_kaya: 10,
	hurricane_pike: 10,
	echo_sabre: 10,
	diffusal_blade: 10,
	witch_blade: 10,
	specialists_array: 10,
	harpoon: 10,
	disperser: 10,
	devastator: 10,
	hydras_breath: 10,
	overwhelming_blink: 10,
	swift_blink: 10,
	arcane_blink: 10,
	skadi: 10,
	//Neutral artifacts
	occult_bracelet: 11,
	kobold_cup: 11,
	chipped_vest: 11,
	polliwog_charm: 11,
	dormant_curio: 11,
	duelist_gloves: 11,
	weighted_dice: 11,
	ash_legion_shield: 11,
	dagger_of_ristul: 11,
	stonefeather_satchel: 11,
	possessed_mask: 11,
	foragers_kit: 11,
	//T2
	essence_ring: 11,
	mana_draught: 11,
	poor_mans_shield: 11,
	searing_signet: 11,
	pogo_stick: 11,
	defiant_shell: 11,
	crippling_crossbow: 11,
	medallion_of_courage: 11,
	seeds_of_serenity: 11,
	//T3
	serrated_shiv: 11,
	gunpowder_gauntlets: 11,
	jidi_pollen_bag: 11,
	psychic_headband: 11,
	unrelenting_eye: 11,
	cloak_of_flames: 11,
	spellslinger: 11,
	stormcrafter: 11,
	partisans_brand: 11,
	//T4
	giant_maul: 11,
	rattlecage: 11,
	idol_of_screeauk: 11,
	flayers_bota: 11,
	metamorphic_mandible: 11,
	dandelion_amulet: 11,
	enchanters_bauble: 11,
	prophets_pendulum: 11,
	conjurers_catalyst: 11,
	//T5
	desolator_2: 11,
	fallen_sky: 11,
	demonicon: 11,
	minotaur_horn: 11,
	spider_legs: 11,
	riftshadow_prism: 11,
	dezun_bloodrite: 11,
	divine_regalia: 11,
	harmonizer: 11,
	heavy_blade: 11,
	//Neutral enchantments
	enhancement_brawny: 12,
	enhancement_tough: 12,
	enhancement_alert: 12,
	enhancement_mystical: 12,
	enhancement_quickened: 12,
	enhancement_vital: 12,
	enhancement_crude: 12,
	enhancement_nimble: 12,
	enhancement_keen_eyed: 12,
	enhancement_titanic: 12,
	enhancement_greedy: 12,
	enhancement_timeless: 12,
	enhancement_hulking: 12,
	enhancement_audacious: 12,
	enhancement_feverish: 12,
	enhancement_manic: 12,
	enhancement_evolved: 12,
	enhancement_fleetfooted: 12,
	enhancement_vampiric: 12,
} as const satisfies Record<ItemLabel, GroupKey>

type NeutralItemTier = 1 | 2 | 3 | 4 | 5
type EnhancementAvailability = {
	tiers: [NeutralItemTier, NeutralItemTier],
	heroTypes: AttributeLabel[]
}
export const ENCHANTMENT_AVAILABILITY = {
	enhancement_brawny: {tiers: [1, 4], heroTypes: ['str', 'agi']},
	enhancement_tough: {tiers: [1, 4], heroTypes: ['str', 'int']},
	enhancement_alert: {tiers: [1, 4], heroTypes: ['agi', 'all']},
	enhancement_mystical: {tiers: [1, 4], heroTypes: [ATTRIBUTES., '']},
	enhancement_quickened: {},
	enhancement_vital: 12,
	enhancement_crude: 12,
	enhancement_nimble: 12,
	enhancement_keen_eyed: 12,
	enhancement_titanic: 12,
	enhancement_greedy: 12,
	enhancement_timeless: 12,
	enhancement_hulking: 12,
	enhancement_audacious: 12,
	enhancement_feverish: 12,
	enhancement_manic: 12,
	enhancement_evolved: 12,
	enhancement_fleetfooted: 12,
	enhancement_vampiric: 12
} as const satisfies Record<ItemLabel, EnhancementAvailability>