import { ATTRIBUTE, type AttributeIdx, type Binding, type ConstEnum, type IdData, type IdMap, type Ids } from "../types/BoundTypes"
import type { ItemKey } from "./bindings"



export const GROUPS = {
	0: {key:'CONS', name: 'consumables'},
	1: {key:'ATTR', name: 'attributes'},
	2: {key:'EQUI', name: 'equipment'},
	3: {key:'MISC', name: 'miscellaneous'},
	4: {key:'SECR', name: 'secret shop'},
	5: {key:'ACCE', name: 'accessories'},
	6: {key:'SUPP', name: 'support'},
	7: {key:'MAGI', name: 'magical'},
	8: {key:'ARMO', name: 'armor'},
	9: {key:'WEAP', name: 'weapons'},
	10:{key:'ARMA', name: 'armaments'},
	11:{key:'ARTI', name: 'neutral artifacts'},
	12:{key:'ENCH', name: 'neutral enchantments'},
	13:{key:'UNIT', name: 'unit specific'},
	14:{key:'OUT', name: 'retired'},
	15:{key:'WIP', name: 'not implemented'},
} as const satisfies Ids<IdData<'name'>>

type GroupIdx = keyof typeof GROUPS
export const GROUP = getIdMap(GROUPS, 'key')
const {
	CONS, ATTR, EQUI, MISC, SECR, ACCE, SUPP, MAGI, ARMO, WEAP, ARMA, ARTI, ENCH
} = GROUP


export const GROUP_BY_ITEM = {
	//BASICS
	//Consumables
	tpscroll: CONS,
	clarity: CONS,
	faerie_fire: CONS,
	smoke_of_deceit: CONS,
	ward_observer: CONS,
	ward_sentry: CONS,
	enchanted_mango: CONS,
	flask: CONS,
	tango: CONS,
	blood_grenade: CONS,
	dust: CONS,
	bottle: CONS,
	infused_raindrop: CONS,
	aghanims_shard: CONS,
	//Attributes
	branches: ATTR,
	gauntlets: ATTR,
	slippers: ATTR,
	mantle: ATTR,
	circlet: ATTR,
	belt_of_strength: ATTR,
	boots_of_elves: ATTR,
	robe: ATTR,
	crown: ATTR,
	ogre_axe: ATTR,
	blade_of_alacrity: ATTR,
	staff_of_wizardry: ATTR,
	diadem: ATTR,
	ghost: ATTR,
	//Equipment
	quelling_blade: EQUI,
	ring_of_protection: EQUI,
	blades_of_attack: EQUI,
	orb_of_frost: EQUI,
	gloves: EQUI,
	chainmail: EQUI,
	broadsword: EQUI,
	blight_stone: EQUI,
	blitz_knuckles: EQUI,
	splintmail: EQUI,
	claymore: EQUI,
	orb_of_venom: EQUI,
	javelin: EQUI,
	helm_of_iron_will: EQUI,
	mithril_hammer: EQUI,
	//Misc.
	ring_of_regen: MISC,
	sobi_mask: MISC,
	wind_lace: MISC,
	magic_stick: MISC,
	fluffy_hat: MISC,
	wizard_hat: MISC,
	boots: MISC,
	voodoo_mask: MISC,
	shawl: MISC,
	shadow_amulet: MISC,
	gem: MISC,
	lifesteal: MISC,
	cloak: MISC,
	chasm_stone: MISC,
	blink: MISC,
	//Secret shop
	ring_of_health: SECR,
	void_stone: SECR,
	talisman_of_evasion: SECR,
	platemail: SECR,
	ring_of_tarrasque: SECR,
	tiara_of_selemene: SECR,
	hyperstone: SECR,
	demon_edge: SECR,
	vitality_booster: SECR,
	energy_booster: SECR,
	point_booster: SECR,
	relic: SECR,
	reaver: SECR,
	eagle: SECR,
	mystic_staff: SECR,
	ultimate_orb: SECR,
	//UPGRADES
	//accessories
	magic_wand: ACCE,
	bracer: ACCE,
	wraith_band: ACCE,
	null_talisman: ACCE,
	power_treads: ACCE,
	soul_ring: ACCE,
	orb_of_corrosion: ACCE,
	falcon_blade: ACCE,
	phase_boots: ACCE,
	pers: ACCE,
	mask_of_madness: ACCE,
	oblivion_staff: ACCE,
	travel_boots: ACCE,
	hand_of_midas: ACCE,
	moon_shard: ACCE,
	soul_booster: ACCE,
	//Support
	ring_of_basilius: SUPP,
	headdress: SUPP,
	urn_of_shadows: SUPP,
	tranquil_boots: SUPP,
	arcane_boots: SUPP,
	mekansm: SUPP,
	essence_distiller: SUPP,
	ancient_janggo: SUPP,
	pavise: SUPP,
	guardian_greaves: SUPP,
	spirit_vessel: SUPP,
	boots_of_bearing: SUPP,
	solar_crest: SUPP,
	glimmer_cape: SUPP,
	holy_locket: SUPP,
	pipe: SUPP,
	//Magical
	veil_of_discord: MAGI,
	rod_of_atos: MAGI,
	cyclone: MAGI,
	phylactery: MAGI,
	bloodstone: MAGI,
	gungir: MAGI,
	wind_waker: MAGI,
	angels_demise: MAGI,
	force_staff: MAGI,
	aether_lens: MAGI,
	meteor_hammer: MAGI,
	dagon: MAGI,
	ultimate_scepter: MAGI,
	crellas_crozier: MAGI,
	octarine_core: MAGI,
	orchid: MAGI,
	refresher: MAGI,
	ethereal_blade: MAGI,
	sheepstick: MAGI,
	bloodthorn: MAGI,
	//Armor
	buckler: ARMO,
	vanguard: ARMO,
	blade_mail: ARMO,
	helm_of_the_dominator: ARMO,
	vladmir: ARMO,
	crimson_guard: ARMO,
	armlet: ARMO,
	helm_of_the_overlord: ARMO,
	consecrated_wraps: ARMO,
	aeon_disk: ARMO,
	lotus_orb: ARMO,
	black_king_bar: ARMO,
	shivas_guard: ARMO,
	sphere: ARMO,
	assault: ARMO,
	heart: ARMO,
	//Weapons
	lesser_crit: WEAP,
	mage_slayer: WEAP,
	heavens_halberd: WEAP,
	desolator: WEAP,
	revenants_brooch: WEAP,
	basher: WEAP,
	maelstrom: WEAP,
	invis_sword: WEAP,
	greater_crit: WEAP,
	abyssal_blade: WEAP,
	mjollnir: WEAP,
	silver_edge: WEAP,
	bfury: WEAP,
	nullifier: WEAP,
	manta: WEAP,
	radiance: WEAP,
	rapier: WEAP,
	monkey_king_bar: WEAP,
	butterfly: WEAP,
	satanic: WEAP,
	//Armaments
	sange: ARMA,
	yasha: ARMA,
	kaya: ARMA,
	dragon_lance: ARMA,
	kaya_and_sange: ARMA,
	sange_and_yasha: ARMA,
	yasha_and_kaya: ARMA,
	hurricane_pike: ARMA,
	echo_sabre: ARMA,
	diffusal_blade: ARMA,
	witch_blade: ARMA,
	specialists_array: ARMA,
	harpoon: ARMA,
	disperser: ARMA,
	devastator: ARMA,
	hydras_breath: ARMA,
	overwhelming_blink: ARMA,
	swift_blink: ARMA,
	arcane_blink: ARMA,
	skadi: ARMA,
	//Neutral artifacts
	occult_bracelet: ARTI,
	kobold_cup: ARTI,
	chipped_vest: ARTI,
	polliwog_charm: ARTI,
	dormant_curio: ARTI,
	duelist_gloves: ARTI,
	weighted_dice: ARTI,
	ash_legion_shield: ARTI,
	dagger_of_ristul: ARTI,
	stonefeather_satchel: ARTI,
	possessed_mask: ARTI,
	foragers_kit: ARTI,
	//T2
	essence_ring: ARTI,
	mana_draught: ARTI,
	poor_mans_shield: ARTI,
	searing_signet: ARTI,
	pogo_stick: ARTI,
	defiant_shell: ARTI,
	crippling_crossbow: ARTI,
	medallion_of_courage: ARTI,
	seeds_of_serenity: ARTI,
	//T3
	serrated_shiv: ARTI,
	gunpowder_gauntlets: ARTI,
	jidi_pollen_bag: ARTI,
	psychic_headband: ARTI,
	unrelenting_eye: ARTI,
	cloak_of_flames: ARTI,
	spellslinger: ARTI,
	stormcrafter: ARTI,
	partisans_brand: ARTI,
	//T4
	giant_maul: ARTI,
	rattlecage: ARTI,
	idol_of_screeauk: ARTI,
	flayers_bota: ARTI,
	metamorphic_mandible: ARTI,
	dandelion_amulet: ARTI,
	enchanters_bauble: ARTI,
	prophets_pendulum: ARTI,
	conjurers_catalyst: ARTI,
	//T5
	desolator_2: ARTI,
	fallen_sky: ARTI,
	demonicon: ARTI,
	minotaur_horn: ARTI,
	spider_legs: ARTI,
	riftshadow_prism: ARTI,
	dezun_bloodrite: ARTI,
	divine_regalia: ARTI,
	harmonizer: ARTI,
	heavy_blade: ARTI,
	//Neutral enchantments
	enhancement_brawny: ENCH,
	enhancement_tough: ENCH,
	enhancement_alert: ENCH,
	enhancement_mystical: ENCH,
	enhancement_quickened: ENCH,
	enhancement_vital: ENCH,
	enhancement_crude: ENCH,
	enhancement_nimble: ENCH,
	enhancement_keen_eyed: ENCH,
	enhancement_titanic: ENCH,
	enhancement_greedy: ENCH,
	enhancement_timeless: ENCH,
	enhancement_hulking: ENCH,
	enhancement_audacious: ENCH,
	enhancement_feverish: ENCH,
	enhancement_manic: ENCH,
	enhancement_evolved: ENCH,
	enhancement_fleetfooted: ENCH,
	enhancement_vampiric: ENCH,
} as const satisfies Record<ItemKey, GroupIdx>

type NeutralItemTier = 1 | 2 | 3 | 4 | 5
type EnhancementAvailability = {
	tiers: [NeutralItemTier, NeutralItemTier?],
	heroTypes: AttributeIdx[]
}

const {STR, AGI, INT, UNI} = ATTRIBUTE
export const ENCHANTMENT_AVAILABILITY = {
	enhancement_brawny: {tiers:[1, 4], heroTypes:[STR, AGI]},
	enhancement_tough: {tiers:[1, 4], heroTypes:[STR, INT]},
	enhancement_alert: {tiers:[1, 4], heroTypes:[AGI, UNI]},
	enhancement_mystical: {tiers:[1, 4], heroTypes:[INT, UNI]},
	enhancement_quickened: {tiers:[1, 4], heroTypes:[STR, AGI, INT, UNI]},
	enhancement_vital: {tiers:[1], heroTypes:[STR, AGI, INT, UNI]},
	enhancement_crude: {tiers:[2, 4], heroTypes:[STR]},
	enhancement_nimble: {tiers:[2, 4], heroTypes:[AGI]},
	enhancement_keen_eyed: {tiers:[2, 4], heroTypes:[INT]},
	enhancement_titanic: {tiers:[2, 4], heroTypes:[UNI]},
	enhancement_greedy: {tiers:[2, 3], heroTypes:[STR, AGI, INT, UNI]},
	enhancement_timeless: {tiers:[4, 5], heroTypes:[STR, AGI, INT, UNI]},
	enhancement_hulking: {tiers:[5], heroTypes:[STR]},
	enhancement_audacious: {tiers:[5], heroTypes: [AGI]},
	enhancement_feverish: {tiers:[5], heroTypes: [INT]},
	enhancement_manic: {tiers:[5], heroTypes: [UNI]},
	enhancement_evolved: {tiers:[5], heroTypes: [STR, AGI, INT, UNI]},
	enhancement_fleetfooted: {tiers:[5], heroTypes: [STR, AGI, INT, UNI]},
	enhancement_vampiric: {tiers:[5], heroTypes: [STR, AGI, INT, UNI]}
} as const satisfies Record<ItemKey, EnhancementAvailability>